# Generated by Django 3.0.8 on 2020-11-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=12, unique=True, verbose_name='客户名称')),
                ('customer_type', models.CharField(choices=[('A', 'A类客户'), ('B', 'B类客户'), ('C', 'C类客户')], max_length=2, verbose_name='客户分类')),
                ('customer_phone', models.CharField(max_length=11, verbose_name='手机号码')),
                ('customer_mail', models.CharField(max_length=20, verbose_name='电子邮箱')),
                ('customer_address', models.CharField(max_length=100, verbose_name='详细地址')),
            ],
        ),
    ]
